### ISSUE TITLE
Events marked as undefined

### ISSUE THREAD

**Issue by drinkius** [Kochava/kochava-tracker-ios-sdk-cocoapod#4]
I've registered the client:

> var trackerDict: [AnyHashable: Any] = [:]
trackerDict[kKVAParamAppGUIDStringKey] = "the_correct_key"
trackerDict[kKVAParamLogLevelEnumKey] = kKVALogLevelEnumTrace
KochavaTracker.shared.configure(withParametersDictionary: trackerDict, delegate: self)

Creating the events as follows:

> let e = KochavaEvent() // Also tried KochavaEvent(eventTypeEnum: .custom)!
        e.nameString = event
        e.userNameString = label
        e.date = Date()
        KochavaTracker.shared.send(e)

Analytics shows correctly _SessionBegin and other system events, but all the custom ones seem to be attributed to `Undefined` category. What can be the issue?

Here is the log:

https://gist.github.com/drinkius/1bac958fdb39a412944a7edd70d9d321

**Comment by johnbushnell** [comment]
You do always want to use the designated constructor method, i.e. KochavaEvent(eventTypeEnum: .custom), but the basic issue is that you want to use customEventNameString instead of nameString.  The property nameString is intended to be used for generic name parameters, i.e. human names, city names, etc.  The property customEventNameString works in conjunction with an eventTypeEnum of .custom to define a custom event name.  You would additionally use the property nameString if you wanted to also associate some other name with the event.  Does that make sense?  Try the following:

**Comment by drinkius** [comment]
Thanks a lot! Checking it out as we speak. 

Was copying the Android setup our team used and the naming conventions seem to be a little bit different there

**Comment by johnbushnell** [comment]
Yes, you're correct, they're a little different.  The Android SDK does not have a public property customEventNameString, but has a constructor that takes in the equivalent string as a parameter.

**Comment by drinkius** [comment]
All worked well, thanks!
