### ISSUE TITLE
KochavaTracker property sdkVersionString returns null

### ISSUE THREAD

**Issue by sandervandenbrink** [Kochava/kochava-tracker-ios-sdk-cocoapod#5]
I'm trying to get the value of sdkVersionString from KochavaTracker but am getting a null value.

**Comment by johnbushnell** [comment]
Hi sandervandenbrink,

Please be advised that the sdkVersionString method returns nil if it is called prior to configuring the tracker.  This behavior is like this because the version string may be augmented with an extension from a wrapper SDK, and so the sdkVersionString is otherwise considered invalid (or undefined) until the moment at which that information would have had the opportunity to have been injected.

Does that resolve your question?

**Comment by sandervandenbrink** [comment]
Hi John,

When is the tracker considered configured? I can get the version in the tracker:didRetrieveAttributionDictionary: delegate method but this call is only invoked on initial start up. 

Thanks

**Comment by johnbushnell** [comment]
The tracker is considered configured immediately after calling instance method: 

`configure(withParametersDictionary: [AnyHashable: Any], delegate: KochavaTrackerDelegate?)`

If you are not using the shared instance, then it is considered configured immediately after using the designated initialization method:

`KochavaTracker? (parametersDictionary: [AnyHashable: Any], delegate: KochavaTrackerDelegate?)`

You are welcome to call sdkVersionString in the delegate method tracker:didRetrieveAttributionDictionary:, but that will occur substantially later- i.e. usually 7-10 seconds after configuring the tracker, and only when there is internet access.

John

**Comment by sandervandenbrink** [comment]
That is what I tried in my first attempt but there seems to be a slight delay/or sync issue in setting the version property. Directly getting the value after configureWithParametersDictionary gives null but by getting it in a async dispatch does give a value.

**Comment by johnbushnell** [comment]
Hi sandervandenbrink,

You are correct.  While this has been fixed in the next version of the SDK, previous versions would not always reliably allow this value to be retrieved if called immediately after configuring the tracker.  Now that it has been improved this slipped my mind in our previous conversation.  If you ask for the sdkVersionString immediately after configuring the tracker your version is experiencing a race condition with the full starting of the tracker on a background thread.  It's not clean, but if you were to async after some reasonable period of time you'd be able to safely retrieve it.The next version of the SDK is planned for release around the end of the year, and it addresses this use case.

**Comment by sandervandenbrink** [comment]
Alright, all clear then. Thanks for the help!
